Add logs
Eira/canyon-notifier pull request #20
Opened 2022-05-17 08:28 UTC by Eira

close #18

2022-05-17 11:15 UTC, esemi requested changes
Хорошая работа! Немножко вкусовщины закинул правками и можно мержить)

2022-05-17 11:15 UTC, esemi commented on README.md
> +# Logs configuration
Кажется в доке писать логичнее девелоперские настройки (как запустить приложение локально) и в самих сеттингсах описание настроек (коментом, если нужно).

А эта дока выглядит как урок написания кода на питоне)

2022-05-17 11:15 UTC, esemi commented on app/storage.py
>      # todo unit test
Я бы ещё `# todo implement` добавил, чтобы не забыть реализовать функцию)

2022-05-17 11:15 UTC, esemi commented on app/storage.py
>      # todo unit test
Я бы ещё `# todo implement` добавил, чтобы не забыть реализовать функцию)

2022-05-17 11:15 UTC, esemi commented on app/update.py
> +            logging.warning(f'empty catalog found!')
Может быть стоит в таком случае (когда каталог пустой получили) вообще прервать обновление? Может через некоторое время данные появятся и не будет ситуации, когда у нас каталог то полный то пустой)

2022-05-17 11:15 UTC, esemi commented on app/update.py
> +        logging.info(f'{items_deleted} old bikes was deleted.')
Кмк стоит строчки лога объединить в одну строку

2022-05-18 20:04 UTC, Eira commented on README.md
> +# Logs configuration
fixed

2022-05-18 20:04 UTC, Eira commented on app/storage.py
>      # todo unit test
fixed

2022-05-18 20:04 UTC, Eira commented on app/storage.py
>      # todo unit test
fixed

2022-05-18 20:05 UTC, Eira commented on app/update.py
> +            logging.warning(f'empty catalog found!')
fixed

2022-05-18 20:09 UTC, Eira commented on app/update.py
> +        logging.info(f'{items_deleted} old bikes was deleted.')
fix

2022-05-18 20:23 UTC, esemi approved these changes

2022-05-18 20:24 UTC, merged