7 new bot
Eira/canyon-notifier pull request #27
Opened 2022-06-04 21:26 UTC by Eira

close #5

2022-06-05 19:29 UTC, esemi requested changes

2022-06-05 19:29 UTC, esemi commented on README.md
> +CanyonNotifierTest
Давай оставим в ридми только боевого бота ссылкой на него?
Тестовый то неважно какой - какой токен скормишь - тот бот и будет на команды отвечать)

2022-06-05 19:29 UTC, esemi commented on README.md
> +
дебаг какой-то в ридми)

2022-06-05 19:29 UTC, esemi commented on app/bot.py
> +API_TOKEN = app_settings.bot_token
зачем константа на уровне модуля?

2022-06-05 19:29 UTC, esemi commented on app/bot.py
> +bot = Bot(token=API_TOKEN)
этот код лучше унести в __main__, пример можно посмотреть у меня в другом боте https://github.com/esemi/stonks/blob/master/app/bot_app.py#L71

2022-06-05 19:29 UTC, esemi commented on app/bot.py
> +    answer_text: str = """
Может всё таки через join?

https://github.com/esemi/stonks/blob/master/app/bot_app.py#L15

2022-06-05 19:29 UTC, esemi commented on app/bot.py
> +async def echo(message: types.Message) -> None:
wat?

2022-06-05 19:29 UTC, esemi commented on app/bot.py
> +    logging.basicConfig(level=logging.INFO)
давай логгинг сделаем по аналогии с фоновой таской апдейта каталога?

Чтобы он в дебаг режим умел

2022-06-05 19:42 UTC, Eira commented on README.md
> +CanyonNotifierTest
done

2022-06-05 19:45 UTC, Eira commented on README.md
> +
done

2022-06-05 19:49 UTC, Eira commented on app/bot.py
> +API_TOKEN = app_settings.bot_token
done

2022-06-05 20:06 UTC, Eira commented on app/bot.py
> +bot = Bot(token=API_TOKEN)
done

2022-06-05 20:06 UTC, Eira commented on app/bot.py
> +async def echo(message: types.Message) -> None:
done

2022-06-05 20:13 UTC, Eira commented on app/bot.py
> +    answer_text: str = """
done

2022-06-05 20:16 UTC, Eira commented on app/bot.py
> +    logging.basicConfig(level=logging.INFO)
done

2022-06-05 20:20 UTC, esemi requested changes
Пример тестиков на хендлеры бота туть)

https://github.com/esemi/stonks/blob/master/tests/bot_app/test_handlers.py

2022-06-05 20:20 UTC, esemi commented on app/bot.py
> +def main() -> None:
тестик хочу)

2022-06-05 20:20 UTC, esemi commented on app/bot.py
> +async def send_welcome(message: types.Message) -> None:
тестик хочу)

2022-06-12 19:57 UTC, Eira commented on app/bot.py
> +async def send_welcome(message: types.Message) -> None:
написала

2022-06-12 19:58 UTC, Eira commented on app/bot.py
> +def main() -> None:
done

2022-06-12 20:04 UTC, esemi requested changes

2022-06-12 20:04 UTC, esemi commented on pyproject.toml
> +pytest-mock = "^3.7.0"
пусть это будет tool.poetry.dev-dependencies зависимость

на проде то оно не нужно

poetry add -D

2022-06-12 20:10 UTC, Eira commented on pyproject.toml
> +pytest-mock = "^3.7.0"
done

2022-06-12 20:11 UTC, esemi approved these changes

2022-06-12 20:16 UTC, merged