32 bike notification
Eira/canyon-notifier pull request #37
Opened 2022-09-19 08:53 UTC by Eira

2022-09-19 09:55 UTC, esemi requested changes
умничка!)

2022-09-19 09:55 UTC, esemi commented on app/bike_model.py
> +class SubscribeBikeFamily:
наверное лучше Subscription ?

2022-09-19 09:55 UTC, esemi commented on app/bot.py
> +        '/unsubscribe - not to receive messages about bike family.',
пока лишнее

2022-09-19 09:55 UTC, esemi commented on app/bot.py
> +class SubscribeBikeFamilyName(StatesGroup):
я бы назвал CreateSubscription

других подписок всё равно нет и не предвидится, а процесс стейт то для процесса создания подписки

2022-09-19 09:55 UTC, esemi commented on app/bot.py
> +    """Allow user to cancel action via /cancel command"""
наверное стоит добавить эту команду в ридми для функции подписки

2022-09-19 09:55 UTC, esemi commented on app/bot.py
> +async def remove_subscription(message: types.Message) -> None:
я бы вынес за рамки этого мержа

2022-09-19 09:55 UTC, esemi commented on app/bot.py
> +async def show_subscriptions(message: types.Message) -> None:
аналогично - таска не об этом

2022-09-19 09:55 UTC, esemi commented on app/bot.py
> +    storage = MemoryStorage()
это надо заменить на редис сторадж - иначе все стейты будут слетать при рестарте бота. Не очень критично, но раз уж редис у нас уже есть - вай нот?

2022-09-19 09:55 UTC, esemi commented on app/bot.py
> +# у каждой подписки индивид id
Лучше унести в коменты к таске в терекере)

2022-09-19 09:55 UTC, esemi commented on tests/test_bot.py
> +
лишняя пустая строка, патерн ААА =)

2022-09-19 09:55 UTC, esemi commented on tests/test_bot.py
> +    mock = mocker.spy(app.bot, 'create_subscription')
лучше назвать мок подробнее - он тут не один же

2022-09-19 09:55 UTC, esemi commented on tests/test_bot.py
> +    assert mock.call_count == 1
давай ещё проверим, что у стейта вызвали финиш?

2022-09-19 09:55 UTC, esemi commented on tests/test_bot.py
> +    message_mock = AsyncMock()
переменная ради использования в одном месте. Может inline ?

2022-09-21 09:42 UTC, Eira commented on app/bike_model.py
> +class SubscribeBikeFamily:
done

2022-09-21 09:44 UTC, Eira commented on app/bot.py
> +        '/unsubscribe - not to receive messages about bike family.',
was commented

2022-09-21 09:48 UTC, Eira commented on app/bot.py
> +class SubscribeBikeFamilyName(StatesGroup):
renamed

2022-09-21 09:56 UTC, Eira commented on app/bot.py
> +    """Allow user to cancel action via /cancel command"""
Right! added.

2022-09-21 09:59 UTC, Eira commented on app/bot.py
> +# у каждой подписки индивид id
good idea

2022-09-21 10:00 UTC, Eira commented on tests/test_bot.py
> +
done

2022-09-21 10:29 UTC, Eira commented on tests/test_bot.py
> +    mock = mocker.spy(app.bot, 'create_subscription')
done

2022-09-21 10:31 UTC, Eira commented on tests/test_bot.py
> +    message_mock = AsyncMock()
А вот тут не согласна, используется дважды.

2022-09-21 10:34 UTC, Eira commented on tests/test_bot.py
> +    assert mock.call_count == 1
точно, но пока не понимаю как

2022-09-21 11:26 UTC, esemi commented on app/storage.py
> +    # Todo test
сделали же?

2022-09-21 11:28 UTC, esemi commented on tests/test_bot.py
> +    assert mock.call_count == 1
Ну он же мокирован, state_mock есть в тесте - так что просто проверить что у него вызвали метод финиш один раз?

2022-09-23 09:47 UTC, Eira commented on app/bot.py
> +async def remove_subscription(message: types.Message) -> None:
done

2022-09-23 09:51 UTC, esemi approved these changes

2022-09-23 09:51 UTC, merged