34 show subscription list
Eira/canyon-notifier pull request #38
Opened 2022-10-31 09:29 UTC by Eira

#34 close

2022-10-31 10:48 UTC, esemi requested changes
Крутяк) Остались мелочи

2022-10-31 10:48 UTC, esemi commented on app/bot/subscription_handlers.py
> +    # todo вывести сообщение о пустом списке
туду нужно доделать перед мержем)

2022-10-31 10:48 UTC, esemi commented on app/bot/subscription_handlers.py
> +    await message.answer('Press the button to delete subscription:', reply_markup=inline_kb1)
может быть `select subscription for delete`?

2022-10-31 10:48 UTC, esemi commented on app/storage.py
> +    await db_pool.sadd(f'chat_id_{chat_id}', subscription_item.subscribe_id)  # todo test
ключи в редисе пусть уж будут одинаково с префиксом нашего проекта

смотри на SUBSCRIPTION_KEY как пример

2022-10-31 10:48 UTC, esemi commented on app/storage.py
> +    subscribe_id_list = await db_pool.smembers(f'chat_id_{chat_id}')
тоже самое с ключём

2022-10-31 10:48 UTC, esemi commented on app/storage.py
> +    # todo test for empty bd
тудушки требуют тестов)

2022-10-31 10:48 UTC, esemi commented on app/storage.py
> +async def subscriptions_from_db(chat_id: int) -> List[SubscriptionBikeFamily]:
я бы назвал функцию get_subscriptions

и так понятно откуда достаём, мы же уже в модуле стораджа

2022-10-31 10:48 UTC, esemi commented on app/storage.py
> +    await db_pool.srem(f'chat_id_{chat_id}', subscribe_id)
тоже ключ без префикса

2022-10-31 10:48 UTC, esemi commented on tests/test_bot.py
> +    mock_usage_counter = mocker.spy(app.bot.subscription_handlers, 'create_subscription')
теперь create_subscription нету в модуле app.bot.subscription_handlers

теперь там используется эта функция уже из модуля app.storage =)

2022-10-31 10:48 UTC, esemi commented on tests/test_bot.py
> +    # todo написать нормально может и тут фикстура нужна
кмк можно использовать готовую фикстуру fixture_prefilled_subscription, она за собой и почистит

2022-10-31 10:48 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> +    # assert
забыли сделать)

2022-10-31 10:48 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> +    res = await subscriptions_from_db(45678765434567)
лучше заменить на заведомо невалидное значение, 0 или там -1 )

2022-11-01 21:54 UTC, Eira commented on app/bot/subscription_handlers.py
> +    await message.answer('Press the button to delete subscription:', reply_markup=inline_kb1)
я бы так оставила

2022-11-01 22:02 UTC, Eira commented on app/storage.py
> +    await db_pool.sadd(f'chat_id_{chat_id}', subscription_item.subscribe_id)  # todo test
готово

2022-11-01 22:04 UTC, Eira commented on app/storage.py
> +    subscribe_id_list = await db_pool.smembers(f'chat_id_{chat_id}')
готово

2022-11-01 22:19 UTC, Eira commented on app/storage.py
> +    await db_pool.srem(f'chat_id_{chat_id}', subscribe_id)
готово

2022-11-01 22:22 UTC, Eira commented on tests/test_bot.py
> +    mock_usage_counter = mocker.spy(app.bot.subscription_handlers, 'create_subscription')
уже вроде в порядке

2022-11-01 22:22 UTC, Eira commented on tests/test_bot.py
> +    # todo написать нормально может и тут фикстура нужна
агась

2022-11-02 10:32 UTC, Eira commented on app/bot/subscription_handlers.py
> +    # todo вывести сообщение о пустом списке
готово

2022-11-02 10:32 UTC, Eira commented on tests/tests_storage/test_subscripton.py
> +    res = await subscriptions_from_db(45678765434567)
готово

2022-11-02 10:33 UTC, Eira commented on tests/tests_storage/test_subscripton.py
> +    # assert
готово

2022-11-02 10:57 UTC, esemi commented on app/storage.py
> +    await db_pool.sadd(SUBSCRIPTION_BY_CHAT_KEY.format(chat_id), subscription_item.subscribe_id)  # todo test
тудушка потерялась

2022-11-02 10:57 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> +    assert res == [
кмк достаточно проверять что идишка совпадает)

но это вкусовщина)

2022-11-02 10:58 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> +async def test_delete_subscription_happy_path(fixture_prefilled_subscription: SubscriptionBikeFamily):
я бы ещё проверил, что удаление уже несуществуюзщей подписки норм отработает, а не падает с ошибкой какой

2022-11-02 11:04 UTC, esemi commented on app/storage.py
> +    chat_id = await db_pool.hget(key_name, 'chat_id')
точно стоит проверить, что тут будет если сабу уже удалили ранее и не упадёт ли вся функция при этом

2022-11-02 11:05 UTC, esemi commented on app/bot/subscription_handlers.py
> +    if current_state is None:
не нужна ли аналогичная проверка в методе process_subscriptions?

2022-11-02 21:35 UTC, Eira commented on tests/tests_storage/test_subscripton.py
> +    assert res == [
done

2022-11-07 08:48 UTC, esemi approved these changes

2022-11-07 09:38 UTC, merged