36 notification for user
Eira/canyon-notifier pull request #39
Opened 2022-11-21 12:15 UTC by Eira

#36 Close

2022-11-22 12:45 UTC, esemi requested changes

2022-11-22 12:45 UTC, esemi commented on app/bike_model.py
> +class Match:
раз уж в этом модуле все модели, то пусть он будет не BIKE_model ?)

2022-11-22 12:45 UTC, esemi commented on app/catalog_updater.py
> +    # todo дописать
тудушка

2022-11-22 12:45 UTC, esemi commented on app/catalog_updater.py
> +        available_bikes_list = _get_new_available_bikes(
не хватает проверки на то, что каталог в БД пустой - в таком случае не стоит спамить всех юзеров)

2022-11-22 12:45 UTC, esemi commented on app/catalog_updater.py
> +        await storage.save_new_available_bikes(available_bikes_list)
всё таки тут логичнее проверить на месте, что список байков появившихся не пустой, чем внутри функции проверять это

2022-11-22 12:45 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> +async def test_save_new_available_bikes_happy_path(fixture_empty_available_bike_list):
не хватает теста на вызов функции с пустым списком

2022-11-22 12:45 UTC, esemi commented on app/storage.py
> +    # todo test
тудушка

2022-11-22 12:45 UTC, esemi commented on app/storage.py
> +    # todo test
тудушка

2022-11-22 12:45 UTC, esemi commented on tests/conftest.py
> +    await save_new_available_bikes(available_bikes_list)
стоит иметь ввиду, что в этой фикстуре ты записываешь только идишки байков в список новопоявившихся. При этом сами байки в редисе не хранятся, это может вызвать падение приложеньки на тестах)

2022-11-22 12:45 UTC, esemi commented on tests/test_subscription_notifier.py
> +# todo разбить на ассерты маленьке
плюс я бы разбил тест на кейсы и на разные тесты.
- ищем подписку в байках и находим
- ищем и не находим
- ищем подписку в пустых байках и не находим

2022-11-22 12:45 UTC, esemi commented on tests/test_subscription_notifier.py
> +from app.bike_model import Bike, SubscriptionBikeFamily, Match
реквестирую разбить этот модуль тестов по аналогии с тестами каталог апдейтера - на пачку файликов.
Будет проще читать

2022-11-22 12:45 UTC, esemi commented on tests/test_subscription_notifier.py
> +    # todo проверку на конкретное сообщение
тудушка

2022-11-22 12:45 UTC, esemi commented on tests/tests_catalog_updater/test_update_catalog.py
> +def test__get_new_available_bikes_happy_path():
лишний андерскор

2022-11-22 12:45 UTC, esemi commented on tests/tests_catalog_updater/test_update_catalog.py
> +def test__get_new_available_bikes_happy_path():
и пусть тогда этот тест будет в отдельном файле, как остальные рядом

2022-11-22 12:45 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> +async def test_get_available_bike_list_happy_path(fixture_prefilled_available_bike_list):
не хватает теста на поведение функции при пустом списке байков в БД

2022-11-22 12:45 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> +async def test_delete_available_bike_list_happy_path(fixture_empty_available_bike_list):
не хватает теста на поведение при удалении уже удалённого байка из списка доступных

2022-11-22 12:45 UTC, esemi commented on tests/tests_storage/test_subscripton.py
> -from app.bike_model import SubscriptionBikeFamily
я бы разбил тесты из этого файла на отдельные файлы по тестируемым функциям

2022-11-22 12:45 UTC, esemi commented on tests/conftest.py
> +async def fixture_prefilled_available_bike_list(fixture_empty_available_bike_list) -> List[Bike]:
возможно стоит добавить сюда на вход фикстуру с предзаполненным байками кааталогом?

2022-11-22 12:45 UTC, esemi commented on app/storage.py
> +            await db_pool.srem(SUBSCRIPTION_AVAILABLE_KEY, bike_id)
srem(key, member, *members)
Remove one or more members from a set.

можно удалить все байки за один вызов редиса)

2022-11-22 12:45 UTC, esemi commented on app/storage.py
> +    # todo test на все подписки
тудуша

2022-11-22 12:45 UTC, esemi commented on app/subscription_notifier.py
> +bot = Bot(token=app_settings.bot_token)
этот код уместно унести в bot_runner.py и сюда импортировать из того модуля

2022-11-22 12:45 UTC, esemi commented on app/subscription_notifier.py
> +    # todo test на невалидные данные (невалидный пользователь)
тест такой нужен, да

2022-11-22 12:45 UTC, esemi commented on app/subscription_notifier.py
> +    # todo test на невалидные данные (невалидный пользователь)
возможно даже стоит удалять подписку, если юзер вдруг невалидным стал

2022-11-22 12:45 UTC, esemi commented on app/subscription_notifier.py
> +        if list_of_matches:
я бы ещё залогировал, сколько метчей нашли

2022-11-23 09:16 UTC, Eira commented on app/catalog_updater.py
> +    # todo дописать
done

2022-11-23 09:42 UTC, Eira commented on tests/conftest.py
> +    await save_new_available_bikes(available_bikes_list)
поправила

2022-11-23 09:51 UTC, Eira commented on tests/test_subscription_notifier.py
> +from app.bike_model import Bike, SubscriptionBikeFamily, Match
сделано

2022-11-23 10:15 UTC, Eira commented on tests/tests_catalog_updater/test_update_catalog.py
> +def test__get_new_available_bikes_happy_path():
готово

2022-11-23 10:17 UTC, Eira commented on tests/conftest.py
> +async def fixture_prefilled_available_bike_list(fixture_empty_available_bike_list) -> List[Bike]:
готово

2022-11-23 10:21 UTC, Eira commented on app/storage.py
> +            await db_pool.srem(SUBSCRIPTION_AVAILABLE_KEY, bike_id)
сделано

2022-11-23 19:44 UTC, Eira commented on tests/tests_storage/test_subscripton.py
> -from app.bike_model import SubscriptionBikeFamily
готово

2022-11-23 20:02 UTC, Eira commented on app/subscription_notifier.py
> +bot = Bot(token=app_settings.bot_token)
готово

2022-11-23 20:09 UTC, Eira commented on app/subscription_notifier.py
> +        if list_of_matches:
должно быть, но надо проверить.

2022-11-23 21:08 UTC, Eira commented on app/catalog_updater.py
> +        available_bikes_list = _get_new_available_bikes(
Проверку сделала

2022-11-24 21:47 UTC, Eira commented on app/catalog_updater.py
> +        await storage.save_new_available_bikes(available_bikes_list)
готово

2022-11-24 21:49 UTC, Eira commented on tests/tests_storage/test_subscripton.py
> +async def test_save_new_available_bikes_happy_path(fixture_empty_available_bike_list):
готово

2022-11-24 21:49 UTC, Eira commented on app/storage.py
> +    # todo test
есть

2022-11-24 21:49 UTC, Eira commented on app/storage.py
> +    # todo test
есть

2022-11-24 21:50 UTC, Eira commented on tests/tests_storage/test_subscripton.py
> +async def test_get_available_bike_list_happy_path(fixture_prefilled_available_bike_list):
есть

2022-11-24 21:51 UTC, Eira commented on tests/tests_storage/test_subscripton.py
> +async def test_delete_available_bike_list_happy_path(fixture_empty_available_bike_list):
вроде есть

2022-11-24 21:51 UTC, Eira commented on app/storage.py
> +    # todo test на все подписки
убрала

2022-11-24 21:58 UTC, Eira commented on tests/test_subscription_notifier.py
> +# todo разбить на ассерты маленьке
Вроде есть

2022-11-27 19:21 UTC, Eira commented on app/subscription_notifier.py
> +    # todo test на невалидные данные (невалидный пользователь)
готово

2022-11-27 19:32 UTC, Eira commented on tests/test_subscription_notifier.py
> +    # todo проверку на конкретное сообщение
готово

2022-11-28 10:58 UTC, esemi requested changes

2022-11-28 10:58 UTC, esemi commented on app/catalog/__init__.py
> +"""# todo description."""
тудушка

2022-11-28 10:58 UTC, esemi commented on app/storage/__init__.py
> +"""# todo description."""
тудушка

2022-11-28 10:58 UTC, esemi commented on tests/test_subscription_notifier/__init__.py
> +"""# todo description."""
в тестах я бы заигнорил просто докстринги, это технический код, а не боевой

2022-11-28 10:58 UTC, esemi commented on tests/test_subscription_notifier/test_main.py
> +# todo подробную проверку
тудушко

2022-11-28 10:58 UTC, esemi commented on tests/tests_catalog_updater/test_main.py
> +# todo сделать проверки на пустой каталог снаружи и на пустой каталог в бд
тудушка

2022-11-28 10:58 UTC, esemi commented on tests/tests_storage/test_get_catalog.py
> +async def test_get_catalog_happy_path(fixture_empty_catalog):
тест с таким названием тут уже есть, они схлопнутся и исполнится последний только (если я верно помню)

2022-11-28 10:58 UTC, esemi commented on app/bot/common_handlers.py
>  async def send_welcome(message: types.Message) -> None:
не нужно ли тут раскоментить новые команды? По крайней мере список подписок вроде нужно?

2022-11-28 10:58 UTC, esemi commented on app/bot/common_handlers.py
>  async def send_welcome(message: types.Message) -> None:
а ещё функция chunks тут есть, но нигде не используется

2022-11-28 10:58 UTC, esemi commented on app/catalog/available_bike_list_operations.py
> +def get_new_available_bikes(old_catalog: List[Bike], actual_catalog: List[Bike]) -> List[Bike]:
можно сделать приватной функцией

2022-11-28 10:58 UTC, esemi commented on app/catalog/catalog_operations.py
> +def get_canyon_catalog_html() -> etree._Element:  # noqa: WPS437
тоже приватная функция

2022-11-28 10:58 UTC, esemi commented on app/catalog/catalog_operations.py
> +def normalize_bike_id(bike_title: str) -> str:
тоже приватная функция

2022-11-28 10:58 UTC, esemi commented on app/catalog/catalog_operations.py
> +def parse_canyon_catalog(html_tree: etree._Element) -> List[Bike]:  # noqa: WPS437, WPS210
тоже приватная функция

2022-11-28 10:58 UTC, esemi commented on app/subscription_notifier.py
> +async def main(throttling_time: float, amount_of_iterations: int) -> int:
давай в файле наверху всегда будут публичные функции, а внутренние - внизу?

2022-11-28 10:58 UTC, esemi commented on app/subscription_notifier.py
> +            await delete_subscription(match.subscription.subscribe_id)
опять не ту функцию вызвали с таким же именем)

2022-11-28 10:58 UTC, esemi commented on app/subscription_notifier.py
> +async def main(throttling_time: float, amount_of_iterations: int) -> int:
а был бы тест на меин +/- полноценный - нашли бы)

2022-11-28 10:58 UTC, esemi commented on tests/tests_storage/test_delete_available_bike_list.py
> +    await delete_available_bike_list(bike_id_set)
У тебя в типе входящего аргумента указано, что будет list, а тут ты шлёшь set

Нужно или сделать одинаково, либо, если тебе не принципиально в функции что именно перебирать, главное чтобы было "перебирабельно" - использовать тип Iterable вместо list

2022-11-28 10:58 UTC, esemi commented on tests/tests_storage/test_delete_available_bike_list.py
> +    await delete_available_bike_list(bike_id_set)
Это во всех тестах в этом модуле, если что

2022-11-28 10:58 UTC, esemi commented on tests/tests_storage/test_insert_actual_catalog.py
>  import pytest
не используется

2022-11-28 11:09 UTC, Eira commented on app/catalog/__init__.py
> +"""# todo description."""
готово

2022-11-28 11:11 UTC, Eira commented on app/storage/__init__.py
> +"""# todo description."""
готово

2022-11-28 11:12 UTC, Eira commented on tests/test_subscription_notifier/__init__.py
> +"""# todo description."""
думаю, оно уже.

2022-11-28 11:16 UTC, Eira commented on tests/tests_storage/test_insert_actual_catalog.py
>  import pytest
Спасибо

2022-11-28 11:17 UTC, Eira commented on app/catalog/catalog_operations.py
> +def parse_canyon_catalog(html_tree: etree._Element) -> List[Bike]:  # noqa: WPS437, WPS210
поправила

2022-11-28 11:31 UTC, Eira commented on app/catalog/available_bike_list_operations.py
> +def get_new_available_bikes(old_catalog: List[Bike], actual_catalog: List[Bike]) -> List[Bike]:
готово

2022-11-28 11:33 UTC, Eira commented on app/catalog/catalog_operations.py
> +def get_canyon_catalog_html() -> etree._Element:  # noqa: WPS437
готово

2022-11-28 11:35 UTC, Eira commented on app/catalog/catalog_operations.py
> +def normalize_bike_id(bike_title: str) -> str:
готово

2022-11-28 11:40 UTC, Eira commented on app/subscription_notifier.py
> +            await delete_subscription(match.subscription.subscribe_id)
Спасибо, поправила.

2022-11-28 11:45 UTC, Eira commented on app/subscription_notifier.py
> +async def main(throttling_time: float, amount_of_iterations: int) -> int:
поправила порядок

2022-11-28 20:48 UTC, Eira commented on tests/test_subscription_notifier/test_main.py
> +# todo подробную проверку
сделано

2022-11-28 21:32 UTC, Eira commented on tests/tests_catalog_updater/test_main.py
> +# todo сделать проверки на пустой каталог снаружи и на пустой каталог в бд
готово

2022-11-28 21:36 UTC, Eira commented on tests/tests_storage/test_get_catalog.py
> +async def test_get_catalog_happy_path(fixture_empty_catalog):
Спасибо

2022-11-28 21:42 UTC, Eira commented on app/bot/common_handlers.py
>  async def send_welcome(message: types.Message) -> None:
Спасибо, поправила.

2022-11-28 21:58 UTC, Eira commented on tests/tests_storage/test_delete_available_bike_list.py
> +    await delete_available_bike_list(bike_id_set)
готово

2022-11-28 22:12 UTC, esemi approved these changes

2022-11-28 22:13 UTC, merged